# Generated by Django 3.1.2 on 2020-10-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='no name')),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='N/A', max_length=6)),
                ('signature', models.CharField(default='N/A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='no name')),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='N/A', max_length=6)),
            ],
        ),
    ]
